### ISSUE TITLE
Chapter6のスクレイピングのコードがうまく動作しませんでした

### ISSUE THREAD

**Issue by tm4roon** [kujirahand/book-rust#1]
# つまづいたところ
- Chapter6のスクレイピングのコードがうまく動きませんでした。
- 以下のようにgetアクセスのprintまではできるのですが、画像のダウンロードまでには至りませんでした。
```
get: https://uta.pw/shodou/index.php?titles&show&title=%E6%B8%A9%E6%B3%89
...
```

# 解決した方法(?)
- 本家のサイトを確認して自分なりに手直ししてみたところ、想定した挙動になりましたので、ご確認いただければと思います。

## 修正した箇所
https://github.com/kujirahand/book-rust/blob/f5b6fbd28943e7c28e3cfdd3ed6ea48128689692/src/ch6/scraping_shodou/src/main.rs#L17-L20

## 変更後
```
    let url = format!(
        "{}/index.php?tag&show&name={}",
        shodou_url,
        urlencoding::encode(title));
```

**Comment by kujirahand** [comment]
ご報告と内容の修正候補をありがとうございました！！

ただ、すみません、書道のサイトに不具合があって、サイトの方がうまく動いていないようでした。
書道のサイトを修正しまして、現在、サンプルそのままでも動くようになっています。

お手数をおかけしました。
また、重ねて、ご報告ありがとうございました。

**Comment by kujirahand** [comment]
ありがとうございます。このIssueを閉じさせていただきます。
ご協力ありがとうございました。

**Comment by tm4roon** [comment]
早々のご対応ありがとうございます！
